global:
  resolve_timeout: 5m
route:
  group_by: ['alert', 'alertname', 'instance', 'job']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 8h
  receiver: 'alerts-tainguyen-devops-all'
  routes:
    - receiver: 'alerts-tainguyen-devops-critical'
      match_re:
        severity: critical
      continue: true
    - receiver: 'alerts-tainguyen-devops-warning'
      match_re:
        severity: warning
      continue: true
    - receiver: 'alerts-tainguyen-devops-all'
      match_re:
        severity: ^(warning|critical)$
      continue: true
receivers:
  - name: 'alerts-tainguyen-devops-warning'
    telegram_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        api_url: "https://api.telegram.org"
        bot_token: "< input bot_token >"
        chat_id: < input chat_id >
        message: '{{ template "telegram.default.message" . }}'
        parse_mode: HTML

  - name: 'alerts-tainguyen-devops-critical'
    telegram_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        api_url: "https://api.telegram.org"
        bot_token: "< input bot_token >"
        chat_id: < input chat_id >
        message: '{{ template "telegram.default.message" . }}'
        parse_mode: HTML

  - name: 'alerts-tainguyen-devops-all'
    telegram_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        api_url: "https://api.telegram.org"
        bot_token: "< input bot_token >"
        chat_id: < input chat_id >
        message: '{{ template "telegram.default.message" . }}'
        parse_mode: HTML

# templates for telegram
templates:
  - '/etc/alertmanager/template/default.tmpl'
