version: '3.3'

networks:
  monitoring-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  loki:
    image: grafana/loki:2.5.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  promtail:
    image: grafana/promtail:2.5.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring-stable.slat.vn"

  karma:
    image: ghcr.io/prymitive/karma:v0.103
    container_name: karma
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9099:8080
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  node_exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  grafana:
    image: grafana/grafana:8.5.10
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-passsword}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.22.0
    container_name: blackbox_exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    networks:
      - monitoring-net
    volumes:
      - ./config_blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"


  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  consul_exporter:
    image: prom/consul-exporter
    container_name: consul_exporter
    command:
      - '--consul.server=127.0.0.1:8500'
    restart: unless-stopped
    ports:
      - 9107:9107
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  sqs_exporter:
    image: jmal98/sqs-exporter:0.1.0
    container_name: sqs_exporter
    environment:
       - AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID>
       - AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY>
       - AWS_REGION=<AWS_REGION>
    restart: unless-stopped
    ports:
      - "9384:9384"
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      
  prometheus_msteams:
    container_name: prometheus_msteams
    image: quay.io/prometheusmsteams/prometheus-msteams:v1.5.0
    restart: unless-stopped
    ports:
       - "2000:2000"
    volumes:
       - ./prometheus-msteams/multi-channel.yml:/tmp/multi-channel.yml
    environment:
       - CONFIG_FILE=/tmp/multi-channel.yml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"

  gitlab-ci-pipelines-exporter:
    image: quay.io/mvisonneau/gitlab-ci-pipelines-exporter:v0.5.3
    container_name: gitlab-ci-pipelines-exporter
    restart: unless-stopped
    ports:
      - 9998:8080
    environment:
      GCPE_GITLAB_TOKEN: <Group Access Persional Token>
      GCPE_CONFIG: /etc/gitlab-ci-pipelines-exporter.yml
      GCPE_INTERNAL_MONITORING_LISTENER_ADDRESS: tcp://127.0.0.1:8082
    volumes:
      - type: bind
        source: ./gitlab-ci-pipelines-exporter.yml
        target: /etc/gitlab-ci-pipelines-exporter.yml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
