version: '3.3'

networks:
  monitoring-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  promtail:
    image: grafana/promtail:3.1.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.101.0
    container_name: victoriametrics
    volumes:
      - ./victoria-metrics-data:/victoria-metrics-data
      - ./victoria-metrics-cache:/logs
    # environment:
    #   - HTTP_AUTH_USER=<HTTP_AUTH_USER>
    #   - HTTP_AUTH_PASS=<HTTP_AUTH_PASS>

    ports:
      - "8428:8428"
    command:
      # - --"--graphiteListenAddr=:2003"
      # - "--opentsdbListenAddr=:4242"
      # - "--httpListenAddr=:8428"
      # - "--influxListenAddr=:8089"
      # - "--vmalert.proxyURL=http://vmalert:8880"
# https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1807 - system victoriametrics distribute
# vmstorage：
      - "--storageDataPath=/victoria-metrics-data"
      - "--retentionPeriod=60d"
      # - "--search.maxUniqueTimeseries=2000000
      # - "--storageDataPath=/lingtian/opt/vmstorage-data"
      # - "--retentionPeriod=1y"
      # - "--bigMergeConcurrency=1"
# vminsert:
      - "--maxLabelsPerTimeseries=500"
      # - "--replicationFactor=2"
      # - "--storageNode=...."
# vmselect:
      # - "--cacheDataPath=/logs"
      # - "--dedup.minScrapeInterval=13s"
      # - "--search.logSlowQueryDuration=15s"
      # - "--search.maxQueryDuration=50s"
      # - "--cacheDataPath=/logs"
      # - "--search.maxQueryLen=1MB"
      # - "--storageNode=......"
# vmagent:
      # - "--promscrape.config=prometheus.yml"
      # - "--remoteWrite.url=xxxxx"
      # - "--http.connTimeout=1000ms"
      # - "--promscrape.maxScrapeSize=250MB"
      # - "--promscrape.suppressDuplicateScrapeTargetErrors"
      # - "--promscrape.cluster.membersCount=9"
      # - "--promscrape.cluster.memberNum=0"
      # - "--promscrape.streamParse=true"
      # - "--promscrape.consulSDCheckInterval=60s"
      # - "--remoteWrite.queues=10"
      # - "--promscrape.cluster.replicationFactor=2"
    networks:
      - external-network
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.no-lockfile'
      - '--web.enable-lifecycle' 
#      - "--web.config.file=/etc/prometheus/web.yml"
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  tricksterv2:
    image: trickstercache/trickster:2
    container_name: tricksterv2
    depends_on:
      - prometheus
      - grafana
    ports:
      - 8480:8480
      - 8481:8481
      - 8483:8483
      - 8484:8484
    volumes:
      - ./docker-compose-data/trickster-config:/etc/trickster
      - ./docker-compose-data/trickster-data:/data/trickster
    restart: always
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  tricksterv1:
    image: tricksterio/trickster:1.1.5
    container_name: tricksterv1
    ports:
      - "8080:8080"
    environment:
      - "ENVIRONMENT=docker-compose"
    volumes:
      - ./trickster/trickster.conf:/etc/trickster/trickster.conf
    depends_on:
      - prometheus
      - grafana
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"
      
  karma:
    image: ghcr.io/prymitive/karma:v6.4.3
    container_name: karma
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9099:8080
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  yace_exporter:
    image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.61.2
    restart: always
    container_name: yace_exporter
    environment:
      AWS_REGION: ap-southeast-1
      AWS_PROFILE: tainguyenbp
    ports:
      - "8080:8080"
    volumes:
      - ./yace_exporter/yace-config.yaml:/tmp/config.yml
      - ./yace_exporter/.aws:/exporter/.aws:ro ## policy
    command:
      - -listen-address=:8080
      - -config.file=/tmp/config.yml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  node_exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-passsword}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox_exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    networks:
      - monitoring-net
    volumes:
      - ./config_blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"


  pushgateway:
    image: prom/pushgateway:v1.9.0
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  consul_exporter:
    image: prom/consul-exporter
    container_name: consul_exporter
    command:
      - '--consul.server=127.0.0.1:8500'
    restart: unless-stopped
    ports:
      - 9107:9107
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  sqs_exporter:
    image: jmal98/sqs-exporter:0.1.0
    container_name: sqs_exporter
    environment:
       - AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID>
       - AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY>
       - AWS_REGION=<AWS_REGION>
    restart: unless-stopped
    ports:
      - "9384:9384"
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"
      
  prometheus_msteams:
    container_name: prometheus_msteams
    image: quay.io/prometheusmsteams/prometheus-msteams:v1.5.0
    restart: unless-stopped
    ports:
       - "2000:2000"
    volumes:
       - ./prometheus-msteams/multi-channel.yml:/tmp/multi-channel.yml
    environment:
       - CONFIG_FILE=/tmp/multi-channel.yml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  gitlab-ci-pipelines-exporter:
    image: quay.io/mvisonneau/gitlab-ci-pipelines-exporter:v0.5.3
    container_name: gitlab-ci-pipelines-exporter
    restart: unless-stopped
    ports:
      - 9998:8080
    environment:
      GCPE_GITLAB_TOKEN: <Group Access Persional Token>
      GCPE_CONFIG: /etc/gitlab-ci-pipelines-exporter.yml
      GCPE_INTERNAL_MONITORING_LISTENER_ADDRESS: tcp://127.0.0.1:8082
    volumes:
      - type: bind
        source: ./gitlab-ci-pipelines-exporter.yml
        target: /etc/gitlab-ci-pipelines-exporter.yml
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:1.0.0
    container_name: "rabbitmq-exporter"
    ports:
        - "9419:9419" # exposed on container providing the port
    environment:
      - RABBIT_URL=http://localhost:15672
      - RABBIT_USER= < RABBIT_USER >
      - RABBIT_PASSWORD= < RABBIT_USER >
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.7.0
    container_name: elasticsearch_exporter
    command:
      - '--es.uri=https://<ELASTICSEARCH_USER>:<ELASTICSEARCH_PASSWORD>@localhost:9200'
    restart: always
    ports:
    - "9114:9114"
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"

  redis-exporter:
    image: oliver006/redis_exporter:v1.61.0
    container_name: redis-exporter
    environment:
      - REDIS_EXPORTER_CHECK_KEYS=*
      - REDIS_EXPORTER_CONNECTION_TIMEOUT=60s
    ports:
      - 9121:9121
    networks:
      - monitoring-net
    labels:
      org.label-schema.group: "monitoring.hotromaytinhit.tech"
      logging: "promtail"
      logging_backend: "loki"
      logging_jobname: "containerlogs"
