# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
    - targets: ['pushgateway:9091']
      labels:
        service: pushgateway
        environments: development
        owner: tainguyenbp
        teams: devops
