on:
  workflow_dispatch:
    inputs:
      service_test1:
        description: 'service_test1'
        type: boolean
        required: false
        default: false
      service_test2:
        description: 'service_test2'
        type: boolean
        required: false
        default: false
      service_test3:
        description: "service_test3"
        type: boolean
        required: false
        default: false

jobs:
  build-deploy-production:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ startsWith(github.ref, 'refs/heads/master') && contains('["tainguyenbp"]', github.actor) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Pre-check step, build & deploy service to the production environments
        if: ${{ github.event.ref == 'refs/heads/master' }}
        run: |
          BRANCH='master'
          ORG='tanguyenbp'
          REPO='prometheus-grafana'
          INPUT_JSON=$(echo '${{ toJson(github.event.inputs) }}')
          echo "INPUT_JSON: $INPUT_JSON"
          
          # Extract descriptions and values of inputs
          # INPUT_DESC=$(echo '${INPUT_JSON}' | jq -r 'to_entries | .[] | "\(.key): \(.value)"')
          INPUT_DESC=$(echo "$INPUT_JSON" | jq -r 'keys_unsorted[]')
          
          # Define list of workflows to trigger
          LIST_NAME_WORKFLOW='service_test1 service_test2 service_test3'

          # Iterate over the descriptions and values
          for ITEM in $INPUT_DESC; do
            # Extract description and value
             WORKFLOW_NAME="${{ github.event.inputs.${ITEM} }}"
             echo "WORKFLOW_NAME parse input: WORKFLOW_NAME"
            # Check if the description corresponds to a workflow in the list and its value is true
            if [[ "$WORKFLOW_NAME" == "true" ]]; then
              echo "Triggering workflow run for $WORKFLOW_NAME..."
              # Trigger the workflow run
              curl -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token $TOKEN" \
                https://api.github.com/repos/${ORG}/${REPO}/actions/workflows/${DESC}.yml/dispatches \
                --data "{\"ref\": \"$BRANCH\"}"
            fi
          done
