on:
  workflow_dispatch:
    inputs:
      service_a:
        description: 'service_a'
        required: true
        default: 'foo'
        type: string
      service_b:
        description: 'service_b'
        type: boolean
        required: false
        default: false
      service_c:
        description: 'service_c'
        type: boolean
        required: false
        default: false
      service_d:
        description: 'service_d'
        type: boolean
        required: false
        default: false
      service_e:
        description: "service_e"
        type: boolean
        required: false
        default: false
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4.1.6
                #if  ${{ github.event.inputs.service_b == 'true' }}
      - run: |
          echo "Var1: ${{ github.event.inputs.service_e }}"
          echo "Var2: ${{ github.event.inputs.service_d }}" 
    
